(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'609ac029-a385-4814-a9f2-e52b53d279a5-map-container',
          componentName:'MapRaw5',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:false
        });
      })({"isPublishMode":true,"lat":"19.228621036670575","lon":"72.97891493402787","address":"Brahmand,  Azad Nagar, Thane, Maharashtra, India","type":"mapbox","isEditMode":false,"zoom":14,"env":"production","mapboxAccessToken":"pk.eyJ1IjoiZ29kYWRkeSIsImEiOiJjaWc5b20wcjcwczAydGFsdGxvamdvYnV0In0.JK9HuO6nAzc8BnMv6W7NBQ","mapboxStyleUrl":"mapbox:\u002F\u002Fstyles\u002Fgodaddy\u002Fciovyeygh0029atm6zbntgxk2","staticContent":{"today":"Today","submitButtonLoadingLabel":"Sending","contactFormResponseErrorMessage":"Something went wrong while sending your message, please try again later","phoneValidationErrorMessage":"Please enter a valid phone number.","defaultCancelButtonLabel":"Cancel","byAppointment":"By Appointment","defaultSubmitButtonLabel":"Send","unsupportedFileType":"Unsupported file type","maxFileCountLimit":"Only {0} files are allowed","closed":"Closed","attachments":"Attachments","termsOfSerivce":"Terms of Service","attachFiles":"Attach Files","recaptchaDisclosure":"This site is protected by reCAPTCHA and the Google {privacyPolicy} and {termsOfSerivce} apply.","emailValidationErrorMessage":"Please enter a valid email address.","mapCTA":"Get directions","privacyPolicyURL":"https:\u002F\u002Fpolicies.google.com\u002Fprivacy","requiredValidationErrorMessage":"Please fill in this required field","openToday":"Open today","couldNotAttach":"Could not attach the following file(s)","totalFileSizeLimit":"Total files would exceed {0} limit","privacyPolicy":"Privacy Policy","termsOfSerivceURL":"https:\u002F\u002Fpolicies.google.com\u002Fterms","fileSizeLimit":"File exceeds {0} limit","emailMaxCountValidationErrorMessage":"Your email address is too long"},"viewDevice":null,"widgetId":"609ac029-a385-4814-a9f2-e52b53d279a5","section":"alt","category":"accent","locale":"en-US","renderMode":"PUBLISH"},{"widgetId":"609ac029-a385-4814-a9f2-e52b53d279a5","widgetType":"CONTACT","widgetPreset":"contact5","order":1,"section":"alt","category":"accent","fontSize":"medium","fontFamily":"alternate","group":"Map","groupType":"Banner","websiteThemeOverrides":{},"widgetThemeOverrides":{}});